In [ ]:

import numpy as np
import cv2

image1 = cv2.imread('imag1.jpg')
image2 = cv2.imread('imag2.jpg')


if image1.shape != image2.shape:
    print("Error: Images must have the same dimensions.")
else:
    
    output_image = cv2.absdiff(image1, image2)
    print(output_image)

    
    cv2.imshow("Absolute Difference", output_image)

    cv2.waitKey(0)
    cv2.destroyAllWindows()


[[[27 35 27]
  [28 36 28]
  [30 38 30]
  ...
  [ 9  1  8]
  [11  1  8]
  [11  1  8]]

 [[29 37 29]
  [30 38 30]
  [32 40 32]
  ...
  [ 9  1  8]
  [10  2  9]
  [10  2  9]]

 [[32 40 32]
  [33 41 33]
  [34 42 34]
  ...
  [ 8  2  9]
  [ 9  3 10]
  [10  2  9]]

 ...

 [[16 25 23]
  [16 25 23]
  [16 25 23]
  ...
  [ 6  8 13]
  [ 5  9 14]
  [ 4 10 15]]

 [[15 24 22]
  [15 24 22]
  [16 25 23]
  ...
  [ 6  8 13]
  [ 2 10 15]
  [ 1 11 16]]

 [[15 24 22]
  [15 24 22]
  [16 25 23]
  ...
  [ 5  9 14]
  [ 2 10 15]
  [ 1 11 16]]]


In [1]:
import cv2
import numpy as np
from skimage.feature import hog
from skimage import exposure


image = cv2.imread('imag1.jpg', cv2.IMREAD_GRAYSCALE)
image = cv2.resize(image, (64, 128))


gradient_x = cv2.Sobel(image, cv2.CV_64F, 1, 0, ksize=1)
gradient_y = cv2.Sobel(image, cv2.CV_64F, 0, 1, ksize=1)


magnitude = np.sqrt(gradient_x**2 + gradient_y**2)
orientation = np.arctan2(gradient_y, gradient_x) * (180 / np.pi) % 180  

cell_size = (8, 8)    
block_size = (2, 2)   
nbins = 9            

hog_features, hog_image = hog(image,
                              orientations=nbins,
                              pixels_per_cell=cell_size,
                              cells_per_block=block_size,
                              block_norm='L2-Hys',
                              visualize=True,
                              transform_sqrt=True)

print(hog_features)


hog_image_rescaled = exposure.rescale_intensity(hog_image, in_range=(0, 10))

cv2.imshow("Original Image", image)
cv2.imshow("HOG Features", hog_image_rescaled)
cv2.waitKey(0)
cv2.destroyAllWindows()


ModuleNotFoundError: No module named 'skimage'

In [2]:
!pip install skimage

  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'


  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      
      *** Please install the `scikit-image` package (instead of `skimage`) ***
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: C:\Users\PC\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
